[tool.ruff]
line-length = 79
exclude = ['venv','.venv', 'migrations']

[tool.isort]
profile = "black"
line_length = 79

[tool.pytest.ini_options]
pythonpath = "."

[tool.blue]
extend-exclude = '(migrations/)'

[tool.taskipy.tasks]
lint = 'ruff . && blue --check . --diff'
format = 'blue .  && isort .'
run = 'uvicorn core.main:app --reload'
pre_test = 'task lint'
test = 'pytest -s -x --cov=core -vv'
post_test = 'coverage html'

