"""autoincrement in table product

Revision ID: 06fabc97d46a
Revises: cabf3ab9135a
Create Date: 2023-08-15 23:12:49.370531

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '06fabc97d46a'
down_revision: Union[str, None] = 'cabf3ab9135a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
