"""exclude column quantity from Product Model v2

Revision ID: cabf3ab9135a
Revises: f20624057da6
Create Date: 2023-08-11 21:53:54.707341

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cabf3ab9135a'
down_revision: Union[str, None] = 'f20624057da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('quantity', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
